version: '3.8'
services:
  mb_rest_api:
    build:
      context: .
# does not work either
#      network: host
    image: 'mb_rest_api:0.1'
    container_name: "mb_rest_api"
    ports:
      - "5000:5000"
# does not work!!!
#    network_mode: host