[default]
debug = false
port = 5100
host = '0.0.0.0'
serverport = 5020
log_level = "INFO"
config_file_path = "DeviceClassConfigs/"

[default.modbus_clients]
"10.10.1.30" = "device_config_files/mb_client_config_hlx.json"

[develop]
log_level = "DEBUG"
