version: '3.8'
services:
  mb_rest_api_server:
    build:
      context: ../..
      dockerfile: /Dockerfile
    image: 'mb_simulator:0.1'
    container_name: "mb_simulator"
    env_file:
      - .env
#    restart: unless-stopped # always
#    ports:
#      - "5000:5000"
# When enabling this, disable ports!
    network_mode: host